#!/bin/bash

set -euo pipefail

root=/Volumes/RAID/var/tmp/mprsyncup
timestamp_file="$root/delete_archives.timestamp"
ts_args="%Y-%m-%dT%H:%M:%S%z"

echo "Running mprsyncup" | @PREFIX@/bin/ts "$ts_args"
@PREFIX@/bin/mprsyncup 2>&1 | @PREFIX@/bin/ts "$ts_args"

if [[ ! -f "$timestamp_file" || ("$(date +%w)" = "1" && $(($(date +%s) - $(stat -f %m "$timestamp_file"))) -gt 86400) ]]; then
    trap 'rm -f -- "$root/current_versions.txt.gz"' EXIT INT TERM
    echo "Finding current archives" | @PREFIX@/bin/ts "$ts_args"
    @PREFIX@/bin/current_versions_for_each_portindex.sh | gzip > "$root/current_versions.txt.gz"
    for packages_dir in /Volumes/RAID@PREFIX@/var/www/macports/packages-private /Volumes/RAID@PREFIX@/var/rsync/macports/packages; do
        echo "Deleting old archives in $packages_dir" | @PREFIX@/bin/ts "$ts_args"
        gzcat "$root/current_versions.txt.gz" | @PREFIX@/bin/delete_old_archives.py "$packages_dir" - 2>/dev/null | xargs rm -fv | sed "s:^$packages_dir/::" | @PREFIX@/bin/ts "$ts_args"
        find "$packages_dir" -type d -empty -print -delete | sed "s:^$packages_dir/::"| @PREFIX@/bin/ts "$ts_args"
    done
    touch "$timestamp_file"
fi

echo "Done" | @PREFIX@/bin/ts "$ts_args"
