map $http_user_agent $bad_ua {
    # Allow TenFourFox, SeaMonkey, ArcticFox, InterWeb and Firefox/115.0,
    # which is still widely used as it was an ESR release
    "~*(TenFourFox|SeaMonkey|ArcticFox|InterWeb|Firefox/115\.0)" 0;

    # Block very agressive spiders and spambots or crawlers that
    # don't identify as bots but cause a lot of load. These Chrome
    # and Firefox versions are all old.
    "~*(Sogou web spider|okhttp|Chrome/(1[0123][0-9]|[1-9]?[0-9])\.|Firefox/([1-9]?[0-9]|1[012][0-9])\.)" 1;

    # Old versions of Internet Explorer, everything < 11 is out of date
    "~*Trident/[3456789]" 1;

    # Nonexistent and outdated Mac OS X versions
    "~*Mac OS X 10_([56]_[012345679]|([789]|10)_[012346789]|1[1234]_[012345789]|15_[01234569])" 1;

    # Impossible combinations of PPC chips with OS versions Apple never released with PPC support
    "~*PPC Mac OS X 10_([789]|1[012345])" 1;

    # AI crawler bots
    "~*(GPTBot|ClaudeBot|OAI-SearchBot|ImagesiftBot|SemanticScholarBot|Ai2Bot-Dolma|Bytespider)" 1;

    # Old versions of iOS on iPhones, iPads, and iPod(!)s
    "~*(iPhone|iPad) OS ([1-9]|1[0123])_" 1;

    # Safari Versions 4 and 5, current is 18
    "~*Version/[45]\.[0-9]+(\.[0-9]+)? Safari/" 1;

    # Opera 8 and 9, current is 118
    "~*^Opera/[89]\." 1;

    # Very outdated versions of Windows:
    # Windows 95
    # Windows 98
    # Windows CE
    # Windows NT 4.0
    # https://simple.wikipedia.org/wiki/Windows_NT_5.x
    # https://simple.wikipedia.org/wiki/Windows_NT_6.x
    "~*Windows (95|98|CE|NT [456]\.)" 1;

    # If no regex matched, allow
    default 0;
}
